//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nilnul.task._web.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public long id { get; set; }
        public string name { get; set; }
        public long semester { get; set; }
    }
}
